remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache  
  - jekyll-sitemap

locale: "ru-RU"
timezone: Europe/Moscow

title: "Скала Страховой Брокер"

logo: "/assets/images/logo.png"

collections:
  reinslogo:
    output: true


description: ""

search: false

defaults:        
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      header:
        overlay_image: "/assets/images/r1.jpg"
       

        
  - scope:
      path: "about"
      type: pages
    values:
      category: "about"
      sidebar:
        nav: "s_about"
        
  - scope:
      path: "services"
      type: pages
    values:
      category: "services"
      sidebar:
        nav: "s_services"
        
  - scope:
      path: "reinsurance"
      type: pages
    values:
      category: "reinsurance"
      sidebar:
        nav: "s_reinsurance"
      header: []
        
  - scope:
      path: "partners"
      type: pages
    values:
      category: "partners"
      sidebar:
        nav: "s_partners"            

