remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  
include: ["_pages"]

site.locale: ru-RU

title: "Страховой Брокер Скала"

description: ""

search: true
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
