remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache  
  - jekyll-sitemap
  - jekyll-offline

locale: "ru-RU"

title: "Скала Страховой Брокер"

logo: "/assets/images/logo.png"


description: ""

search: false

footer:
  links:[]
  
defaults:        
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      header:
        overlay_image: "/assets/images/m2.jpg"
       

        
  - scope:
      path: "about"
      type: pages
    values:
      sidebar:
        nav: "s_about"
        
  - scope:
      path: "services"
      type: pages
    values:
      sidebar:
        nav: "s_services"
        
  - scope:
      path: "reinsurance"
      type: pages
    values:
      sidebar:
        nav: "s_reinsurance"
        
  - scope:
      path: "partners"
      type: pages
    values:
      sidebar:
        nav: "s_partners"            

