remote_theme: mmistakes/minimal-mistakes@4.16.3


# plugins:
#   - jekyll-include-cache
#   - jekyll-sitemap  

markdown: kramdown

kramdown:
   input: GFM
   hard_wrap: false

locale: "ru-RU"
timezone: Europe/Moscow

title: "Скала Страховой Брокер"
en_title: "Skala Reinsurance Brokers"

logo: "/assets/images/logo.png"

description: ""

search: true
search_full_content: true

defaults:

  - scope:
      path: "assets/images/reinslogo"
    values:
      image: true
        
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      header:
        overlay_image: "/assets/images/r1.jpg"
        
  - scope:
      path: "about"
      type: pages
    values:
      place: "about"
      sidebar:
        nav: "s_about"
        
  - scope:
      path: "services"
      type: pages
    values:
      place: "services"
      sidebar:
        nav: "s_services"
        
  - scope:
      path: "reinsurance"
      type: pages
    values:
      place: "reinsurance"
      sidebar:
        nav: "s_reinsurance"
      header: []
        
  - scope:
      path: "partners"
      type: pages
    values:
      place: "partners"
      sidebar:
        nav: "s_partners"

  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
            
  - scope:
      path: "en"
      type: pages
    values:
      lang: en

  - scope:
      path: "en/about"
      type: pages
    values:
      place: "about"
      sidebar:
        nav: "en_about"
        
  - scope:
      path: "en/services"
      type: pages
    values:
      place: "services"
      sidebar:
        nav: "en_services"
        
  - scope:
      path: "en/reinsurance"
      type: pages
    values:
      place: "reinsurance"
      sidebar:
        nav: "en_reinsurance"
      header: []
        
  - scope:
      path: "en/partners"
      type: pages
    values:
      place: "partners"
      sidebar:
        nav: "en_partners"            
